apiVersion: v1
kind: Service
metadata:
  name: vcluster-red
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      nodePort: 30587
      targetPort: 8443
      protocol: TCP
  selector:
    app: vcluster-red
