apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vcluster-red
  labels:
    app: vcluster-red
spec:
  serviceName: vcluster-red-headless
  replicas: 1
  selector:
    matchLabels:
      app: vcluster-red
  template:
    metadata:
      labels:
        app: vcluster-red
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: vcluster-red
      containers:
      - image: rancher/k3s:v1.23.9+k3s1
        name: virtual-cluster
        command:
          - "/bin/k3s"
        args:
          - "server"
          - "--write-kubeconfig=/vcluster-red/kube-config.yaml"
          - "--data-dir=/data"
          - "--disable=traefik,servicelb,metrics-server,local-storage"
          - "--disable-network-policy"
          - "--disable-agent"
          - "--disable-scheduler"
          - "--disable-cloud-controller"
          - "--flannel-backend=none"
          - "--kube-controller-manager-arg=controllers=*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle"  
          - "--service-cidr=10.96.0.0/12"  
        volumeMounts:
          - mountPath: /data
            name: data
      - name: syncer
        image: "loftsh/virtual-cluster:0.0.27"
        args:
          - --service-name=vcluster-red
          - --suffix=vcluster-red
          - --owning-statefulset=vcluster-red
          - --out-kube-config-secret=vcluster-red
        volumeMounts:
          - mountPath: /data
            name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
