kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vcluster-blue-cr
  labels:
    app: vcluster
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "persistentvolumes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "watch", "list"]
