apiVersion: v1
kind: Service
metadata:
  name: vcluster-blue
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      nodePort: 30588
      targetPort: 8443
      protocol: TCP
  selector:
    app: vcluster-blue
