apiVersion: v1
kind: Service
metadata:
  name: vcluster-blue-headless
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  clusterIP: None
  selector:
    app: vcluster-blue
